"""empty message

Revision ID: 324df4ef9b4e
Revises: e1c202b8d04f
Create Date: 2023-03-02 16:49:34.323100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324df4ef9b4e'
down_revision = 'e1c202b8d04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
