"""empty message

Revision ID: 8122bba3d2e1
Revises: 5734c53a37fa
Create Date: 2023-02-27 17:38:30.060637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8122bba3d2e1'
down_revision = '5734c53a37fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_list', schema=None) as batch_op:
        batch_op.drop_constraint('reading_list_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_list', schema=None) as batch_op:
        batch_op.create_unique_constraint('reading_list_user_id_key', ['user_id'])

    # ### end Alembic commands ###
