"""empty message

Revision ID: f02a3bf88217
Revises: 6ed6b2ad2804
Create Date: 2023-03-02 17:36:54.159032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02a3bf88217'
down_revision = '6ed6b2ad2804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_name_fkey', type_='foreignkey')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comments_name_fkey', 'user', ['name'], ['name'])

    # ### end Alembic commands ###
